# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\ronal\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\visualizacion_cultivos\consulta_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ConsultaDialog(object):
    def setupUi(self, ConsultaDialog):
        ConsultaDialog.setObjectName("ConsultaDialog")
        ConsultaDialog.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(ConsultaDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(ConsultaDialog)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.cmbCultivo = QtWidgets.QComboBox(ConsultaDialog)
        self.cmbCultivo.setObjectName("cmbCultivo")
        self.verticalLayout.addWidget(self.cmbCultivo)
        self.label_2 = QtWidgets.QLabel(ConsultaDialog)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.spnProduccion = QtWidgets.QSpinBox(ConsultaDialog)
        self.spnProduccion.setMinimum(0)
        self.spnProduccion.setMaximum(1000)
        self.spnProduccion.setObjectName("spnProduccion")
        self.verticalLayout.addWidget(self.spnProduccion)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnConsultar = QtWidgets.QPushButton(ConsultaDialog)
        self.btnConsultar.setObjectName("btnConsultar")
        self.horizontalLayout.addWidget(self.btnConsultar)
        self.btnCancelar = QtWidgets.QPushButton(ConsultaDialog)
        self.btnCancelar.setObjectName("btnCancelar")
        self.horizontalLayout.addWidget(self.btnCancelar)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(ConsultaDialog)
        QtCore.QMetaObject.connectSlotsByName(ConsultaDialog)

    def retranslateUi(self, ConsultaDialog):
        _translate = QtCore.QCoreApplication.translate
        ConsultaDialog.setWindowTitle(_translate("ConsultaDialog", "Consulta de Zonas de Cultivo"))
        self.label.setText(_translate("ConsultaDialog", "Seleccione el tipo de cultivo:"))
        self.label_2.setText(_translate("ConsultaDialog", "Producción mínima (toneladas):"))
        self.btnConsultar.setText(_translate("ConsultaDialog", "Consultar"))
        self.btnCancelar.setText(_translate("ConsultaDialog", "Cancelar"))
